// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-K7xDSTPYBq7ySC_21vI8jgEuPMZ3rdo',
    appId: '1:141247023943:web:ef391547a4c6888aef5a62',
    messagingSenderId: '141247023943',
    projectId: 'backandbody-14fdd',
    authDomain: 'backandbody-14fdd.firebaseapp.com',
    databaseURL: 'https://backandbody-14fdd-default-rtdb.firebaseio.com',
    storageBucket: 'backandbody-14fdd.firebasestorage.app',
    measurementId: 'G-3MFMXH4PSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKtLbJI197Y75YwL2W9zqQcMzGWvxey_Q',
    appId: '1:141247023943:android:b2cb40519933aba6ef5a62',
    messagingSenderId: '141247023943',
    projectId: 'backandbody-14fdd',
    databaseURL: 'https://backandbody-14fdd-default-rtdb.firebaseio.com',
    storageBucket: 'backandbody-14fdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcopLt8P2oT8na3qdTr7As3_YneyUL6HA',
    appId: '1:141247023943:ios:9714a18237e47322ef5a62',
    messagingSenderId: '141247023943',
    projectId: 'backandbody-14fdd',
    databaseURL: 'https://backandbody-14fdd-default-rtdb.firebaseio.com',
    storageBucket: 'backandbody-14fdd.firebasestorage.app',
    iosBundleId: 'com.example.doctorappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcopLt8P2oT8na3qdTr7As3_YneyUL6HA',
    appId: '1:141247023943:ios:9714a18237e47322ef5a62',
    messagingSenderId: '141247023943',
    projectId: 'backandbody-14fdd',
    databaseURL: 'https://backandbody-14fdd-default-rtdb.firebaseio.com',
    storageBucket: 'backandbody-14fdd.firebasestorage.app',
    iosBundleId: 'com.example.doctorappflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-K7xDSTPYBq7ySC_21vI8jgEuPMZ3rdo',
    appId: '1:141247023943:web:20bc5220c3f72575ef5a62',
    messagingSenderId: '141247023943',
    projectId: 'backandbody-14fdd',
    authDomain: 'backandbody-14fdd.firebaseapp.com',
    databaseURL: 'https://backandbody-14fdd-default-rtdb.firebaseio.com',
    storageBucket: 'backandbody-14fdd.firebasestorage.app',
    measurementId: 'G-TP1QHS7RHT',
  );
}
