import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'firebase_options.dart';  // ✅ Generated by FlutterFire CLI

import 'package:doctorappflutter/AdminPanel/Dashboard/bottomnav/adminnavbottom.dart';
import 'package:doctorappflutter/Auth/authsignupscreen.dart';
import 'package:doctorappflutter/Auth/resetpasswordscreen.dart';
import 'package:doctorappflutter/DashboardScreen/userbottomnav.dart';
import 'package:doctorappflutter/StorageServiceClass/storageservice.dart';
import 'package:doctorappflutter/ahmadswork/Pending_approval.dart';
import 'package:doctorappflutter/splashscreen/frontscreen.dart';
import 'Auth/signinComponents/signinbody.dart';
import 'DashboardScreen/DashboardDetailsScreen/reportsdetails.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized(); // ✅ Required before Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // ✅ Use generated config
  );
  await GetStorage.init();

  String? token = StorageService().readToken();
  runApp(MyApp(token: token));
}

class MyApp extends StatelessWidget {
  final String? token;

  MyApp({required this.token});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Frontscreen(),
    );
  }
}
